### PR TITLE
fix: import from element-plus when autoImports disabled

### LINKED ISSUE #149: nux3中，当禁用自动导入，报错如下：ID_INJECTION_KEY无法找到
ERROR  Pre-transform error: [unimport] failed to find "ID_INJECTION_KEY" imported from "#imports"            14:49:41
  Plugin: nuxt:imports-transform
  File: virtual:nuxt:D%3A%2FworkProject%2Fworks%2Fnovoage-m%2F.nuxt%2Felement-plus-injection.plugin.mjs

"element-plus": "^2.9.8",
"nuxt": "^3.15.4",
"@element-plus/nuxt": "^1.1.1",

### PR DESCRIPTION
**Pull request by Dsaquel**
I think even if the user disable `autoImports` we should keep imports from element-plus to avoid hydration mismatch with injection's and use `globalConfig` from `nuxt.config.ts`
fix #149

### CODE REVIEW

File: src/core/globalConfig.ts [hunk 1]
```diff
@@ -1,14 +1,16 @@
...
-export function resolveGlobalConfig (config: ModuleOptions) {
+export function resolveGlobalConfig (config: ModuleOptions, autoImport?: boolean) {
   const { globalConfig } = config
 
   return {
     filename: `${libraryName}-globalConfig.plugin.mjs`,
     getContents: () => {
-      return `import { defineNuxtPlugin, provideGlobalConfig } from '#imports';
+      let imports = `import { defineNuxtPlugin ${(autoImport || '') && ', provideGlobalConfig'} } from '#imports'`;
+      if(!autoImport) imports = imports.concat("\nimport { provideGlobalConfig } from 'element-plus'")
```
Comment (tolking) [inline src/core/globalConfig.ts:11]: 不能够从 'element-plus' 直接引用内容，应该指向具体的文件。这样应该会引起开发时产生很多不必要的请求

我觉得禁用的时候 `ID_INJECTION_KEY` `ZINDEX_INJECTION_KEY` `provideGlobalConfig` 也应该自动导入，或许可以拆分 `config.ts` 中的 allImports 配置已实现分别导入

Comment (Dsaquel) [reply src/core/globalConfig.ts]: Thanks for advice, i created `baseImports` to address this issue.

**Review by tolking — APPROVED** [review]
Thanks you for your contribution
